Neos:
  Ldap:
    # Allow login based on cached credentials if the directory service is offline
    allowStandinAuthentication: FALSE
    roles:
      default: []
      groupMapping: []
      userMapping: []
    party: []
    defaultContext: []
